//在下面配置好放入common_base里面
var BASE_URL_CONFIG = {
    COMMON_BASE: {

        // TITLETEXT: 'SME微事',
        // BACKGROUND: '#073d93',
        // LOGO: '../static/images/cloud/logo.png',
        // TEXTCOLOR: '#fff',
        // COLOR: '#2569b4',
        // ISTITLE: true,
        // ISTITLELOGO: '../static/images/cloud/logo.png',
        // TITLE: '',
        // ISYUN: true,
        // FOOTERBACKGROUND: '../static//images/cloud/bg.png',
        // ISLEFTLOGO: false,
        // ISLEFTBACKGROUND: '#073d93',
        // ISLEFTIMAGE: '../static/images/cloud/bg.png',
        // LEFTLOGO: '../static/images/cloud/logo.png',
        // DIALOGSKIN: '',
        // DOWNLOADIMAGES: ''

        BACKGROUND: '#00706b url(../static/images/ESWFW066LoginBac.png) center center no-repeat',
        LOGO: '../static/images/ESWFW066Logo.png',
        TEXTCOLOR: '#FFF',
        COLOR: '#09a4a0',
        ISTITLE: true,
        ISYUN: false,
        TITLETEXT: '电力之家',
        ISTITLELOGO: '../static/images/ESWFW066electricityName.png',
        TITLE: '奉献清洁能源   共建和谐社会',
        FOOTERBACKGROUND: '',
        ISLEFTLOGO: true,
        LEFTLOGO: '',
        ISLEFTBACKGROUND: '#00706b',
        ISLEFTIMAGE: '',
        DOWNLOADIMAGES: '../static/images/14731315701.png',
        DIALOGSKIN: 'layui-layer-molv',
    },
    DIAN_LI: {
        BACKGROUND: '#00706b url(../static/images/ESWFW066LoginBac.png) center center no-repeat',
        LOGO: '../static/images/ESWFW066Logo.png',
        TEXTCOLOR: '#FFF',
        COLOR: '#09a4a0',
        ISTITLE: true,
        ISYUN: false,
        TITLETEXT: '电力之家',
        ISTITLELOGO: '../static/images/ESWFW066electricityName.png',
        TITLE: '奉献清洁能源   共建和谐社会',
        FOOTERBACKGROUND: '',
        ISLEFTLOGO: true,
        LEFTLOGO: '',
        ISLEFTBACKGROUND: '#00706b',
        ISLEFTIMAGE: '',
        DOWNLOADIMAGES: '../static/images/14731315701.png',
        DIALOGSKIN: 'layui-layer-molv',
    },
    SHI_JI_ZHI_GUANG: {
        BACKGROUND: '#fff',
        LOGO: '../static/images/copticmm/logo.png',
        TEXTCOLOR: '#34B6E7',
        COLOR: '#34B6E7',
        ISTITLE: true,
        ISTITLELOGO: '../static/images/copticmm/logo.png',
        TITLE: '',
        ISYUN: false,
        TITLETEXT: '世纪之光',
        FOOTERBACKGROUND: '../static//images/copticmm/home_slogen.png',
        ISLEFTLOGO: false,
        ISLEFTBACKGROUND: '#34B6E7',
        DOWNLOADIMAGES: '../static/images/copticmm/14731315701.png',
        ISLEFTIMAGE: '../static/images/copticmm/pic-1.png',
        LEFTLOGO: '../static/images/copticmm/left_logo.png',
        DIALOGSKIN: '',
    },
    YUN_CLOUD: {
        TITLETEXT: '团队协作-管理员后台管理系统',
        BACKGROUND: '#073d93',
        LOGO: '../static/images/cloud/logo.png',
        TEXTCOLOR: '#fff',
        COLOR: '#2569b4',
        ISTITLE: true,
        ISTITLELOGO: '../static/images/cloud/logo.png',
        TITLE: '',
        ISYUN: true,
        FOOTERBACKGROUND: '../static//images/cloud/bg.png',
        ISLEFTLOGO: false,
        ISLEFTBACKGROUND: '#073d93',
        ISLEFTIMAGE: '../static/images/cloud/bg.png',
        LEFTLOGO: '../static/images/cloud/logo.png',
        DIALOGSKIN: '',
        DOWNLOADIMAGES: ''

    }
}

module.exports = BASE_URL_CONFIG;